core/egov-localization/src/main/java/org/egov/domain/service/MessageService.java
core/egov-localization/src/main/java/org/egov/persistence/repository/MessageRepository.java
core/egov-localization/src/main/java/org/egov/persistence/repository/builder/MessageRepositoryQueryBuilder.java
core/egov-localization/src/main/java/org/egov/web/contract/CreateMessagesRequest.java
core/egov-localization/src/main/java/org/egov/web/contract/DeleteMessagesRequest.java
core/egov-localization/src/main/java/org/egov/web/contract/Message.java
core/egov-localization/src/main/java/org/egov/web/contract/NewMessagesRequest.java
core/egov-localization/src/main/java/org/egov/web/controller/MessageController.java
core/egov-localization/src/test/java/org/egov/domain/service/MessageServiceTest.java
core/egov-localization/src/test/java/org/egov/persistence/repository/MessageRepositoryTest.java
core/egov-localization/src/test/java/org/egov/persistence/repository/builder/MessageRepositoryQueryBuilderTest.java
core/egov-localization/src/test/java/org/egov/web/controller/MessageControllerTest.java
core/egov-localization/src/test/resources/createNewMessageRequest.json
core/egov-localization/src/test/resources/createNewMessageRequestMissingMandatoryFields.json
core/egov-localization/src/test/resources/createNewMessageRequestMissingMandatoryFieldsResponse.json
core/egov-localization/src/test/resources/createNewMessageResponse.json
core/egov-localization/src/test/resources/mandatoryFieldsMissingErrorResponse.json

Hey,
I have pushed the code to my remote branch. Can you please let me know if anything has to be added
Regards,
Darshan Nagesh

Create, Update and Delete Message APIs along with Test Cases

---

core/egov-accesscontrol/src/main/resources/db/migration/seed/V20170620132623__pgrmaster_role_action_mapping.sql
core/egov-location/pom.xml
core/egov-workflow/src/main/java/org/egov/workflow/domain/model/PersistRouter.java
core/egov-workflow/src/main/java/org/egov/workflow/persistence/repository/builder/RouterQueryBuilder.java
core/egov-workflow/src/main/java/org/egov/workflow/util/PgrMasterConstants.java
core/egov-workflow/src/main/java/org/egov/workflow/web/controller/RouterController.java
core/egov-workflow/src/test/java/org/egov/workflow/domain/service/RouterServiceTest.java
core/egov-workflow/src/test/java/org/egov/workflow/persistence/repository/RouterRepositoryTest.java
core/egov-workflow/src/test/java/org/egov/workflow/repository/rowmapper/PersistRouterRowMapperTest.java
core/egov-workflow/src/test/java/org/egov/workflow/web/controller/RouterControllerTest.java
core/egov-workflow/src/test/resources/routerRequestInfo.json
core/egov-workflow/src/test/resources/routerResponse.json

create and update router test cases and few api changes for router
Please ignore the pom.xml of egov-location in this merge.

Router test cases and update url change for router

---

web/react-pgr-web/src/components/framework/components/UiTable.js
web/react-pgr-web/src/components/framework/search.js

Hello Sourabh,
We added time being work around for workflow i.e. added action buttons into search tables, please review and if you are fine merge into master.
If any questions please do let me know. 
Thanks

Legal case  Added Actions column with buttonArray

---

web/react-pgr-web/src/components/framework/components/UiFileTable.js
web/react-pgr-web/src/components/framework/components/UiMultiFieldTable.js

FileTable Upload and download
Bug Fixes
1. MultiFieldTable while clicking on add new row showing same existing row values
2. while setting data to MultiFieldTable it is showing only single record.

FileTable Features and MultiFieldTable Bug Fixes

---

core/egov-data-uploader/src/main/java/org/egov/dataupload/controller/DataUploadController.java
core/egov-data-uploader/src/main/java/org/egov/dataupload/model/DefinitionTestRequest.java
core/egov-data-uploader/src/main/java/org/egov/dataupload/model/DefinitionTestResponse.java
core/egov-data-uploader/src/main/java/org/egov/dataupload/service/DataUploadService.java
core/egov-data-uploader/src/main/java/org/egov/dataupload/utils/DataUploadUtils.java

To test a config send request in below format
```json
{
"headers": ["Vendor Name","Serviced locations","Registration No","Supplier No","Supplier Name","Agency Name","Mobile No","Contact No","FaxNo","Email","Address","Supplier TinNo","GST","Aadhar No","Agreement","Services Offered","Details"],
"data": [
["Anmol","12","REG12345","SUP4567","ACF","QWE","1234567890","9123456780","9876543210","xyz@gmail.com","aadfghjkertyhyjkxcvbnvgnm","TIN12356","GST1246","ADR123466","qdgy","Process 3", "wdhjj"]
],
"definition": {
"defName": "create vendor-create case",
"apiRequest": {
"RequestInfo": {},
"vendors": [
{
"tenantId": "",
"name": "",
"servicedLocations": [
{
"code": ""
}
],
"registrationNo": "",
"supplier": {
"tenantId": "",
"supplierNo": "",
"name": "",
"agencyName": "",
"mobileNo": "", …
```

Uploader service config tester branch.

---

core/egov-location/pom.xml
core/egov-location/src/test/java/org/egov/boundary/persistence/repository/BoundaryRepositoryTest.java
core/egov-location/src/test/java/org/egov/boundary/web/controller/BoundaryControllerTest.java
core/egov-location/src/test/java/org/egov/boundary/web/controller/BoundaryTypeControllerTest.java
core/egov-location/src/test/java/org/egov/boundary/web/controller/CityControllerTest.java
core/egov-location/src/test/java/org/egov/boundary/web/controller/HierarchyTypeControllerTest.java

Fix for failing test cases post tracer addition.
Pom cleanup.

Test cases fix

---

core/egov-filestore/src/main/java/org/egov/filestore/domain/service/StorageService.java
core/egov-filestore/src/main/java/org/egov/filestore/persistence/repository/ArtifactRepository.java
core/egov-filestore/src/main/java/org/egov/filestore/persistence/repository/AwsS3Repository.java
core/egov-filestore/src/main/java/org/egov/filestore/persistence/repository/FileStoreJpaRepository.java
core/egov-filestore/src/main/java/org/egov/filestore/web/controller/StorageController.java
core/egov-filestore/src/main/resources/application.properties

Filestore rainmaker feature

---

core/egov-location/pom.xml
core/egov-location/src/main/java/org/egov/boundary/domain/model/Location.java
core/egov-location/src/main/java/org/egov/boundary/domain/service/GoogleLocationService.java
core/egov-location/src/main/java/org/egov/boundary/domain/service/MdmsService.java
core/egov-location/src/main/java/org/egov/boundary/domain/service/TenantService.java
core/egov-location/src/main/java/org/egov/boundary/persistence/repository/MdmsRepository.java
core/egov-location/src/main/java/org/egov/boundary/util/BoundaryConstants.java
core/egov-location/src/main/java/org/egov/boundary/web/contract/Geography.java
core/egov-location/src/main/java/org/egov/boundary/web/contract/TenantResponse.java
core/egov-location/src/main/java/org/egov/boundary/web/contract/tenant/exception/InvalidTenantDetailsException.java
core/egov-location/src/main/java/org/egov/boundary/web/contract/tenant/model/City.java
core/egov-location/src/main/java/org/egov/boundary/web/contract/tenant/model/Tenant.java
core/egov-location/src/main/java/org/egov/boundary/web/contract/tenant/model/TenantType.java
core/egov-location/src/main/java/org/egov/boundary/web/controller/GeographicalController.java
core/egov-location/src/main/java/org/egov/boundary/web/controller/TenantController.java
core/egov-location/src/test/java/org/egov/boundary/domain/service/GoogleLocationServiceTest.java
docs/egov-location/contracts/v11-0-0.yml

Resolve Tenant Id from Lat/Lng 
- Initial Commit
- Requires env variable [GMAPS_API_KEY] containing the Google Maps API key to be used
Geographical Search
- Minor changes to Geography object
Location Contract updated

Resolve Tenant Id from Lat/Lng Initial Commit and other minor fixes

---

core/egov-location/src/main/java/org/egov/boundary/domain/service/MdmsService.java
core/egov-location/src/main/java/org/egov/boundary/domain/service/TenantService.java
core/egov-location/src/main/java/org/egov/boundary/util/BoundaryConstants.java

Resolve Tenant Id from Lat/Lng

---

core/egov-location/src/main/resources/application.properties

Corrects kafka Module name, enable kafka for egov-location module

Fix Kafka Module name

---

propertytax/pt-property/src/main/resources/db/migration/main/V20171016115250__ptis_noticedate_to_timestamp.sql

Property Tax
Fix - Incorrect date format parsing being attempted, use correct datestyle

PT Fix - Incorrect date format parsing being attempted, use correct datestyle

---

hr-2.0/hr-employee-v2/src/main/java/org/egov/eis/model/Assignment.java
hr-2.0/hr-employee-v2/src/main/java/org/egov/eis/model/bulk/Employee.java
hr-2.0/hr-employee-v2/src/main/java/org/egov/eis/repository/AssignmentRepository.java
hr-2.0/hr-employee-v2/src/main/java/org/egov/eis/repository/MdmsRepository.java
hr-2.0/hr-employee-v2/src/main/java/org/egov/eis/repository/rowmapper/AssignmentRowMapper.java
hr-2.0/hr-employee-v2/src/main/java/org/egov/eis/repository/rowmapper/AssignmentTableRowMapper.java
hr-2.0/hr-employee-v2/src/main/java/org/egov/eis/repository/rowmapper/EmployeeInfoRowMapper.java
hr-2.0/hr-employee-v2/src/main/java/org/egov/eis/service/DesignationService.java
hr-2.0/hr-employee-v2/src/main/java/org/egov/eis/service/EmployeeService.java
hr-2.0/hr-employee-v2/src/main/java/org/egov/eis/web/contract/DesignationGetRequest.java
hr-2.0/hr-employee-v2/src/main/java/org/egov/eis/web/validator/EmployeeAssignmentValidator.java
hr-2.0/hr-employee-v2/src/main/resources/application.properties
hr-2.0/hr-employee-v2/src/main/resources/db/migration/main/V20180418144447__hr_employee_designation_alter_type.sql
hr-2.0/hr-employee-v2/src/test/java/org/egov/eis/service/AssignmentServiceTest.java

Move Designations to MDMS
Use Designation Code instead of ID

HR-V2 Designation Changes

---

hr-2.0/hr-employee-v2/src/main/java/org/egov/eis/repository/builder/EmployeeQueryBuilder.java

Fix search by Department Codes

HR 2.0 - Search by Dept Codes Fix

---

hr-2.0/hr-employee-v2/src/main/resources/config/application-config.properties

Default employee page size change

Default employee page size change

---

core/egov-user/src/main/java/org/egov/user/security/oauth2/custom/CustomAuthenticationProvider.java
core/egov-user/src/main/resources/application.properties

Add featured to enabled fixed otp for automation

Add featured to enabled fixed otp for automation

---

core/egov-user/src/main/java/org/egov/user/security/oauth2/custom/CustomAuthenticationProvider.java
core/egov-user/src/main/resources/application.properties
core/egov-user/src/test/resources/application.properties

Fixed otp for automation

---

core/egov-pg-service/pom.xml

Add snapshot repo

---

core/egov-notification-sms/pom.xml
core/egov-notification-sms/src/main/java/org/egov/web/notification/sms/services/ExternalSMSService.java
core/egov-notification-sms/src/main/resources/application.properties
core/egov-notification-sms/src/test/java/org/egov/web/notification/sms/consumer/SmsNotificationListenerTest.java
core/egov-notification-sms/src/test/java/org/egov/web/notification/sms/models/RequestContextTest.java
core/egov-notification-sms/src/test/java/org/egov/web/notification/sms/services/ExternalSMSServiceTest.java

Added support for GET request in SMS Service for Punjab

Added support for GET request in SMS Service

---

rainmaker/rainmaker-pgr/src/main/java/org/egov/pgr/utils/ReportUtils.java

Added a null check for dbResponse to avoid throwing an exception at get()

PGR reports null handling in getDBResponse

---

libraries/tracer/readme.md
libraries/tracer/src/main/java/org/egov/tracer/ExceptionAdvise.java
libraries/tracer/src/main/java/org/egov/tracer/http/CorrelationIdFilter.java
libraries/tracer/src/main/java/org/egov/tracer/model/Error.java

Handles new exceptions:
- JSON Parsing Error (When JSON body has errors)
- JSON Mapping Error (When object type is wrong)
- Wrong media Type Error
- Handle tracer's internal exception (if tracer code raises exception)
- Handle resource exception exception when one of the dependent services is down
Other changes
- Code optimization
- Fixed bug where body is set to null on JSON parsing error

Tracer exception handling enhancements and bug fixes

---

core/egov-data-uploader/src/main/resources/application.properties

also changed application.properties to have employee_create.json only  as upload.json.path

uplaoder added .gitkeep in internal directoy

---

reportinfra/report/src/main/java/org/egov/report/repository/ReportRepository.java
reportinfra/report/src/main/java/org/egov/report/repository/builder/ReportQueryBuilder.java

Added the functionality to have userid in reports yml. ($userid)

Userid in reports infra

---

gateway/zuul/src/main/java/org/egov/Utils/ExceptionUtils.java
gateway/zuul/src/main/java/org/egov/exceptions/CustomException.java
gateway/zuul/src/main/java/org/egov/filters/error/ErrorFilterFilter.java
gateway/zuul/src/main/java/org/egov/filters/post/ResponseErrorFilter.java
gateway/zuul/src/main/java/org/egov/filters/pre/AuthFilter.java
gateway/zuul/src/main/java/org/egov/filters/pre/AuthPreCheckFilter.java
gateway/zuul/src/main/java/org/egov/filters/pre/RbacFilter.java
gateway/zuul/src/main/java/org/egov/filters/pre/RequestEnrichmentFilter.java
gateway/zuul/src/test/java/org/egov/filters/pre/AuthFilterTest.java
gateway/zuul/src/test/java/org/egov/filters/pre/AuthPreCheckFilterTest.java
gateway/zuul/src/test/java/org/egov/filters/pre/RbacFilterTest.java

Zuul error handling

---

docs/rainmaker/property-tax/reports/reports.yml

Changes in yml
- show total for column functionality
- Fixed fromDate, toDate not working for some reports

Updated PT reports

---

docs/rainmaker-pgr/reports/reports.yml

- DescriptionReport for (PGR-ADMIN, GRO)
- EmployeeReport for (EMPLOYEE)

PGR Reports

---

core/egov-notification-sms/pom.xml
core/egov-notification-sms/src/main/java/org/egov/web/notification/sms/services/ExternalSMSService.java
core/egov-notification-sms/src/main/resources/application.properties
core/egov-notification-sms/src/test/java/org/egov/web/notification/sms/consumer/SmsNotificationListenerTest.java
core/egov-notification-sms/src/test/java/org/egov/web/notification/sms/models/RequestContextTest.java
core/egov-notification-sms/src/test/java/org/egov/web/notification/sms/services/ExternalSMSServiceTest.java

Sms get request support for Punjab

Sms get request support for Punjab

---

rainmaker/pt-calculator-v2/src/main/java/org/egov/pt/calculator/service/EstimationService.java
rainmaker/pt-calculator-v2/src/main/java/org/egov/pt/calculator/util/CalculatorUtils.java
rainmaker/pt-calculator-v2/src/main/java/org/egov/pt/calculator/web/models/property/User.java

@tarunlalwani please merge it.

plotsize and assessment query fixed

---

hr-2.0/hr-employee-v2/src/main/java/org/egov/eis/config/PropertiesManager.java
hr-2.0/hr-employee-v2/src/main/java/org/egov/eis/service/EmployeeService.java
hr-2.0/hr-employee-v2/src/main/resources/application.properties

posting message to finance after successful employee creation

employee sub-ledger changes

---

docs/finance/report/report.yml
docs/reportinfra/report/reportFileLocations.txt
docs/reportinfra/report/reportFileLocationsv1.txt

finance(erp)  ReceiptRegister report changes

Finance coexistence

---

gateway/zuul/pom.xml

Zuul version upgrade for reports to 1.4.6

Zuul version upgrade for reports to 1.4.6

---

hr-2.0/hr-employee-v2/src/main/java/org/egov/eis/model/User.java
hr-2.0/hr-employee-v2/src/main/resources/application.properties
hr-2.0/hr-employee-v2/src/test/java/org/egov/eis/web/controller/NomineeControllerTest.java

Fix for hr-employee update not working. 
- The uuid was missing from model
- The falling unit test needed fix
- The `application.properties` had wrong url for update

Fix employee update

---

rainmaker/tl-services/src/main/java/org/egov/tl/repository/rowmapper/TLRowMapper.java
rainmaker/tl-services/src/main/java/org/egov/tl/service/EnrichmentService.java
rainmaker/tl-services/src/main/java/org/egov/tl/util/NotificationUtil.java
rainmaker/tl-services/src/main/java/org/egov/tl/util/TLConstants.java
rainmaker/tl-services/src/main/java/org/egov/tl/web/models/TradeLicense.java
rainmaker/tl-services/src/main/java/org/egov/tl/workflow/ActionValidator.java
rainmaker/tl-services/src/main/java/org/egov/tl/workflow/TLWorkflowService.java
rainmaker/tl-services/src/main/java/org/egov/tl/workflow/WorkflowConfig.java
rainmaker/tl-services/src/main/java/org/egov/tl/workflow/WorkflowIntegrator.java

status changed from enum to string

---

rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/service/WorkflowService.java
rainmaker/pt-services-v2/src/main/resources/db/migration/main/V20190129111734_eg_pt_add_index_ddl.sql

Removed search validation wf

---

rainmaker/pt-calculator-v2/src/main/java/org/egov/pt/calculator/service/EstimationService.java

Add tax head category for round off

Add tax head category for round off

---

rainmaker/pt-services-v2/src/main/resources/db/migration/main/V20190129111734__eg_pt_add_index_ddl.sql

added indexes in pt

---

rainmaker/egov-hrms/src/main/java/org/egov/hrms/service/MDMSService.java
rainmaker/egov-hrms/src/main/java/org/egov/hrms/utils/ErrorConstants.java
rainmaker/egov-hrms/src/main/java/org/egov/hrms/utils/HRMSConstants.java
rainmaker/egov-hrms/src/main/java/org/egov/hrms/web/validator/EmployeeValidator.java

Feature hrms

---

gateway/nginx-pb/start.sh

Adding nginx config for pmidc only for prod.

Adding pmidc for nginx

---

rainmaker/tl-services/src/main/java/org/egov/tl/service/BoundaryService.java
rainmaker/tl-services/src/main/java/org/egov/tl/service/EnrichmentService.java

Search criteria in user was not correct
Unique user uuid are sent in search

Bug fix for default search

---

reportinfra/report/src/main/java/org/egov/swagger/model/ColumnDetail.java

UI wants to display the columns having type as currency as commas added in indian currency format. Type currency will be passed in YML in sourcecolumns

Reports: Added enum for currency

---

docs/rainmaker/property-tax/reports/reports.yml
reportinfra/report/src/main/java/org/egov/report/service/ReportService.java
reportinfra/report/src/main/java/org/egov/swagger/model/ColumnDetail.java

Reports: Initial, Min, Max values added in PT receipt register report

ReportInfra: Initial, Min and Max values function added

---

dev-utils/playground.sh
gateway/nginx-pb/start.sh

Nginx Kibana config updated from echo to printf for new line character

Nginx Kibana config updated

---

docs/billingservice/contracts/v1-1.yml

additional details type changed to object

---

docs/billingservice/contracts/v1-1.yml

payee changed to payer, receipt details removed

---

rainmaker/pt-services-v2/src/main/java/org/egov/pt/repository/rowmapper/PropertyRowMapper.java

Correction to propertyRowmapper for additionDetails to handle null values

Correction to propertyRowmapper for additionDetails

---

rainmaker/rainmaker-pgr/src/main/java/org/egov/pgr/repository/ReportResponseRowMapper.java
rainmaker/rainmaker-pgr/src/main/java/org/egov/pgr/service/GrievanceService.java
rainmaker/rainmaker-pgr/src/main/java/org/egov/pgr/service/NotificationService.java
rainmaker/rainmaker-pgr/src/main/java/org/egov/pgr/utils/PGRConstants.java
rainmaker/rainmaker-pgr/src/main/java/org/egov/pgr/utils/PGRUtils.java
rainmaker/rainmaker-pgr/src/main/java/org/egov/pgr/utils/WorkFlowConfigs.java
rainmaker/rainmaker-pgr/src/main/java/org/egov/pgr/validator/PGRRequestValidator.java

Changes:
1. PGR was using role-name based WF which is now refactored to use role-code based WF. 
2. Transformation logic while indexing is changed to fix the persister delay issue.
3. Javadocs have been added to a few methods in notif service,

refactored name based wf to code based

---

rainmaker/rainmaker-pgr/src/main/resources/application.properties

Changes:
1. endpoint of searcher modified as per new changes

changed searcher path

---

core/egov-apportion-service/src/main/java/org/egov/service/ApportionService.java
core/egov-apportion-service/src/main/java/org/egov/service/apportions/OrderByPriorityApportion.java
core/egov-apportion-service/src/main/java/org/egov/web/models/BillInfo.java
core/egov-apportion-service/src/main/java/org/egov/web/models/TaxAndPayment.java

Added TaxAndPayment object as replacement for collectionMap

added changes in billing contract

---

rainmaker/tl-services/src/main/java/org/egov/tl/util/TradeUtil.java

Added module filter for selecting financial year from MDMS

added module filter in TL

---

core/egov-mdms-create/src/main/resources/master-config.json

Add TL ApplictionType as state level master

Add TL ApplictionType as state level master

---

core/egov-enc-service/Dockerfile
core/egov-enc-service/mvnw
core/egov-enc-service/mvnw.cmd
core/egov-enc-service/pom.xml
core/egov-enc-service/start.sh
core/egov-enc-service/verify.sh

Signed-off-by: rushang7 <rushangdhanesha@gmail.com>

Enc-service : New files for deployment

---

rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/service/EnrichmentService.java
rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/service/UserService.java
rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/service/WorkflowService.java

@nithindv 
Added requestInfo in internal user search call as encryption service requires user roles for  decryption

added requestInfo in user search for encryption

---

rainmaker/tl-services/src/main/java/org/egov/tl/service/PaymentUpdateService.java

Added enrichment method after payment to generate license number after payment
@nithindv

Correction to license number generation after payment

---

rainmaker/tl-services/src/main/java/org/egov/tl/config/TLConfiguration.java
rainmaker/tl-services/src/main/java/org/egov/tl/service/notification/PaymentNotificationService.java
rainmaker/tl-services/src/main/java/org/egov/tl/service/notification/TLNotificationService.java
rainmaker/tl-services/src/main/java/org/egov/tl/util/NotificationUtil.java
rainmaker/tl-services/src/main/java/org/egov/tl/util/TLConstants.java
rainmaker/tl-services/src/main/resources/application.properties

Made changes to notification according to the new workflow of TL
@nithindv

TL_NOTIFICATION

---

rainmaker/tl-services/src/main/java/org/egov/tl/service/notification/TLNotificationService.java

added condition to skip for sendback action

---

rainmaker/tl-services/src/main/java/org/egov/tl/util/TLConstants.java

correction to notification trigger point

---

rainmaker/tl-services/src/main/java/org/egov/tl/validator/TLValidator.java

changes to validations in update

---

rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/service/EnrichmentService.java
rainmaker/tl-services/src/main/java/org/egov/tl/service/TradeLicenseService.java
rainmaker/tl-services/src/main/java/org/egov/tl/validator/TLValidator.java

Tl validto validation

---

core/egov-indexer/src/main/java/org/egov/infra/indexer/service/DataTransformationService.java
core/egov-indexer/src/main/java/org/egov/infra/indexer/service/IndexerService.java
core/egov-indexer/src/main/java/org/egov/infra/indexer/util/IndexerUtils.java
core/egov-indexer/src/main/resources/billingservices-indexer.yml
core/egov-indexer/src/main/resources/collection-indexer.yml
core/egov-indexer/src/main/resources/rainmaker-pgr-indexer.yml
core/egov-indexer/src/main/resources/rainmaker-pt-indexer.yml

Changes -
1. Modified configs for new hrms
2. Added '.egov' to context paths
3. Removed error logs

Indexer patch

---

rainmaker/pt-services-v2/src/main/resources/db/migration/main/V20190403172537__eg_pt_index_searchparam_ddl.sql
rainmaker/tl-services/src/main/java/org/egov/tl/validator/TLValidator.java

Added validation on owner's active status

Tl owner validation

---

rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/config/WorkflowConfig.java
rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/repository/BusinessServiceRepository.java
rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/service/BusinessMasterService.java
rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/service/EnrichmentService.java
rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/web/models/BusinessServiceSearchCriteria.java
rainmaker/egov-workflow-v2/src/main/resources/application.properties

@nithindv 
Added fallback for businessService. If state level flag is true it will split and search on pb and in response will enrich the tenantId

Added statelevel flag for businessService

---

rainmaker/tl-services/src/main/java/org/egov/tl/validator/TLValidator.java

When financial year is changed in update the validTo field is enriched again from MDMS

correction to validTo when financialYear is changed in update

---

rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/service/EnrichmentService.java
rainmaker/tl-services/src/main/java/org/egov/tl/util/NotificationUtil.java
rainmaker/tl-services/src/main/java/org/egov/tl/util/TLConstants.java

@nithindv 
Added notification for cancel

Tl notification

---

rainmaker/egov-workflow-v2/src/main/resources/egov-workflow-v2-persister.yml

updated persister path for bussinessServiceSla

---

rainmaker/pt-services-v2/src/main/java/org/egov/pt/config/PropertyConfiguration.java
rainmaker/pt-services-v2/src/main/java/org/egov/pt/service/NotificationService.java
rainmaker/pt-services-v2/src/main/java/org/egov/pt/service/PaymentNotificationService.java
rainmaker/pt-services-v2/src/main/java/org/egov/pt/util/PropertyUtil.java

Fetching locale from msgId in requestInfo. If not present en_IN is used as default
@GhanshyamRawat 
@nithindv

fetching locale from requestInfo

---

rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/repository/rowmapper/BusinessServiceRowMapper.java
rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/web/models/State.java
rainmaker/egov-workflow-v2/src/main/resources/db/migration/main/V20190411170435__wf_add_isStateUpdatable_ddl.sql
rainmaker/egov-workflow-v2/src/main/resources/egov-workflow-v2-persister.yml

Added isStateUpdatable boolean field added for tl edit feature
@nithindv

Wf isupdatable field

---

rainmaker/tl-calculator/src/main/java/org/egov/tlcalculator/service/CalculationService.java
rainmaker/tl-calculator/src/main/java/org/egov/tlcalculator/web/models/Accessory.java

@nithindv 
Added count in accessory object

added count in accessories

---

rainmaker/pt-services-v2/src/main/java/org/egov/pt/web/models/PropertyDetail.java

added valid annotation in propertyDetail

---

rainmaker/pt-services-v2/src/main/java/org/egov/pt/util/PropertyUtil.java

correction to fetch locale from requestInfo

---

core/egov-indexer/src/main/java/org/egov/infra/indexer/controller/IndexerController.java
core/egov-indexer/src/main/java/org/egov/infra/indexer/service/LegacyIndexService.java
core/egov-indexer/src/main/java/org/egov/infra/indexer/service/ReindexService.java
core/egov-indexer/src/main/java/org/egov/infra/indexer/web/contract/LegacyIndexRequest.java
core/egov-indexer/src/main/java/org/egov/infra/indexer/web/contract/PaginationDetails.java

Merging changes.
1. Reindex from starting offset/
2. Parent-child thread model for indexing
3. API exposed for indexing

Reindex starting offset

---

core/egov-indexer/src/main/java/org/egov/IndexerApplicationRunnerImpl.java
core/egov-indexer/src/main/java/org/egov/infra/indexer/bulkindexer/BulkIndexer.java

code put inside try and removed logs

minor changes

---

rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/repository/BusinessServiceRepository.java
rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/repository/ServiceRequestRepository.java
rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/repository/WorKflowRepository.java
rainmaker/egov-workflow-v2/src/main/java/org/egov/wf/repository/querybuilder/WorkflowQueryBuilder.java

Wf search order

---

libraries/services-common/src/main/java/org/egov/common/contract/request/Role.java

added tenantId in role object

---

core/egov-telemetry/egov-telemetry-kafka-streams/src/main/java/org/egov/telemetry/Main.java
core/egov-telemetry/egov-telemetry-kafka-streams/src/main/java/org/egov/telemetry/config/AppProperties.java
core/egov-telemetry/egov-telemetry-kafka-streams/src/main/resources/application.properties

Create topics with partitions and replication factor given in properties/env vars.

Create topics with partitions and replication factor given in properties/env vars.

---

rainmaker/pt-calculator-v2/src/main/java/org/egov/pt/calculator/service/DemandService.java
rainmaker/pt-calculator-v2/src/main/java/org/egov/pt/calculator/service/ReceiptService.java
rainmaker/pt-calculator-v2/src/main/java/org/egov/pt/calculator/util/CalculatorUtils.java
rainmaker/pt-calculator-v2/src/main/resources/application.properties

Fix interest calc PI-5813
